config/routes.rb
Rails.application.routes.draw do
  resources :trouble911s
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Lockup::Engine, at: '/lockup'
  resources :georeports
  resources :txdotstreets
  resources :txdotlights
  resources :genericcallouts
  resources :citystreets
  resources :watersewers
  resources :animalcontrols
  resources :cchlogs
  resources :daysoffrequests
  resources :ithelptickets
  resources :fleettickets
  resources :radionumbers
  resources :vacationpatrols
  resources :sexoffenders do
    resources :comments
  end
  resources :phonenumbers
  resources :gatecodes
  resources :rollcalls
  resources :sessions
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "/pages/:page" => "pages#show"
  resources :users
  get 'dashboard/index'
  get '/dailydispatch' => 'dailydispatch#index.html.erb'
  root 'dashboard#index'

end

app/models/txdotstreet.rb
class Txdotstreet < ApplicationRecord

  def city_to_string
    city ? 'Yes' : 'No'
  end

  def state_to_string
    state ? 'Yes' : 'No'
  end
  validates :intersection,
            presence: true,
            length: {maximum: 140},
            allow_nil: false
  validates :name,
            presence: true,
            length: {maximum: 140},
            allow_nil: false
  validates :callback,
            presence: true,
            length: {maximum: 140},
            allow_nil: false
  validates :unitassigned,
            presence: true,
            length: {maximum: 140},
            allow_nil: false
  validates :needed,
            length: {maximum: 140},
            allow_nil: false
  validates :problem,
            presence: true,
            length: {maximum: 400 },
            allow_nil: false
  validates :comment,
            presence: true,
            length: {maximum: 400 },
            allow_nil: false
end

app/controllers/txdotstreets_controller.rb
class TxdotstreetsController < ApplicationController
  load_and_authorize_resource
  before_action :set_txdotstreet, only: [:show, :edit, :update, :destroy]

  # GET /txdotstreets
  # GET /txdotstreets.json
  def index
    @txdotstreets = Txdotstreet.all.paginate(:per_page =>15, :page => params[:page])
                        .where("intersection ILIKE ?","%#{params[:address_search]}%").where("name ILIKE ?","%#{params[:name_search]}%").where("callback ILIKE ?","%#{params[:phone_search]}%").where("unitassigned ILIKE ?","%#{params[:unit_search]}%")
  end

  # GET /txdotstreets/1
  # GET /txdotstreets/1.json
  def show
  end

  # GET /txdotstreets/new
  def new
    @txdotstreet = Txdotstreet.new
  end

  # GET /txdotstreets/1/edit
  def edit
  end

  # POST /txdotstreets
  # POST /txdotstreets.json
  def create
    @txdotstreet = Txdotstreet.new(txdotstreet_params)

    respond_to do |format|
      if @txdotstreet.save
        format.html { redirect_to @txdotstreet, notice: 'TX-DOT Street Call-Out was successfully created.' }
        format.json { render :show, status: :created, location: @txdotstreet }
      else
        format.html { render :new }
        format.json { render json: @txdotstreet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /txdotstreets/1
  # PATCH/PUT /txdotstreets/1.json
  def update
    respond_to do |format|
      if @txdotstreet.update(txdotstreet_params)
        format.html { redirect_to @txdotstreet, notice: 'TX-DOT Street Call-Out was successfully updated.' }
        format.json { render :show, status: :ok, location: @txdotstreet }
      else
        format.html { render :edit }
        format.json { render json: @txdotstreet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /txdotstreets/1
  # DELETE /txdotstreets/1.json
  def destroy
    @txdotstreet.destroy
    respond_to do |format|
      format.html { redirect_to txdotstreets_url, notice: 'TX-DOT Street Call-Out was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_txdotstreet
      @txdotstreet = Txdotstreet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def txdotstreet_params
      params.require(:txdotstreet).permit(:intersection, :name, :callback, :unitassigned, :problem, :city, :state, :needed, :comment)
    end
end

app/helpers/txdotstreets_helper.rb
module TxdotstreetsHelper
end

app/views/txdotstreets/_form.html.erb
<%= form_with(model: txdotstreet, local: true) do |form| %>
  <% if txdotstreet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(txdotstreet.errors.count, "error") %> prohibited this txdotstreet callout from being saved:</h2>

      <ul>
      <% txdotstreet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :intersection %>
    <%= form.text_field :intersection, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :callback, "Call Back" %>
    <%= form.text_field :callback, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :unitassigned, "Unit Assigned" %>
    <%= form.text_field :unitassigned, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :problem %>
    <%= form.text_area :problem, maxlength: 400 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.check_box :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.check_box :state %>
  </div>

  <div class="field">
    <%= form.label :needed, "What is needed, if anything?" %>
    <%= form.text_field :needed, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, maxlength: 400 %>
  </div>

  <div class="actions">
    <%= form.submit "Submit"%>
  </div>
<% end %>

app/views/txdotstreets/edit.html.erb
<h1>Editing TX-DOT Street Call-Out</h1>

<%= render 'form', txdotstreet: @txdotstreet %>

<%= link_to 'Show', @txdotstreet %> |
<%= link_to 'Back', txdotstreets_path %>

app/views/txdotstreets/index.html.erb
<p id="notice"><%= notice %></p>
<div id="search">
  <%= form_tag txdotstreets_path, :method => 'get' do %>
    <%= text_field_tag :address_search, params[:address_search], :placeholder => "Address" %>
    <%= text_field_tag :name_search, params[:name_search], :placeholder => "Name" %>
    <%= text_field_tag :phone_search, params[:phone_search], :placeholder => "Callback Number" %>
    <%= text_field_tag :unit_search, params[:unit_search], :placeholder => "Unit Number" %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

<div class="apple_pagination">
  <%= will_paginate @txdotstreets %>
</div>

<center>

<h1>TX-DOT Streets Call-Out</h1>

<table>
  <thead>
    <tr>
      <th>Intersection</th>
      <th>Name</th>
      <th>Call Back</th>
      <th>Unit Assigned</th>
      <th>Problem</th>
      <th>City</th>
      <th>State</th>
      <th>Needed</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @txdotstreets.each do |txdotstreet| %>
      <tr>
        <td><%= txdotstreet.intersection.humanize %></td>
        <td><%= txdotstreet.name.humanize.titleize %></td>
        <td><%= txdotstreet.callback.humanize %></td>
        <td><%= txdotstreet.unitassigned.humanize %></td>
        <td><%= txdotstreet.problem.humanize %></td>
        <td><%= txdotstreet.city_to_string.humanize %></td>
        <td><%= txdotstreet.state_to_string.humanize %></td>
        <td><%= txdotstreet.needed.humanize %></td>
        <td><%= txdotstreet.comment.humanize %></td>
        <td><%= link_to '', txdotstreet , class: "far fa-eye"
        %></td>
        <td><%= link_to '', edit_txdotstreet_path(txdotstreet), class: "far fa-edit"
        %></td>
        <% if can? :delete, :all %>
      <td><%= link_to '', txdotstreet, method: :delete, data: { confirm: 'Are you sure?' }, class: "far fa-trash-alt" %></td>
          <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Call-Out', new_txdotstreet_path %>
  <br />-
  <br />
  <a href="/pages/afterhours.html">Back to After Hours Call-Out</a>
</center>

app/views/txdotstreets/new.html.erb
<h1>New TX-DOT Street Call-Out</h1>

<%= render 'form', txdotstreet: @txdotstreet %>

<%= link_to 'Back', txdotstreets_path %>

app/views/txdotstreets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Intersection:</strong>
  <%= @txdotstreet.intersection.humanize %>
</p>

<p>
  <strong>Name:</strong>
  <%= @txdotstreet.name.humanize.titleize %>
</p>

<p>
  <strong>Call Back:</strong>
  <%= @txdotstreet.callback.humanize %>
</p>

<p>
  <strong>Unit Assigned:</strong>
  <%= @txdotstreet.unitassigned.humanize %>
</p>

<p>
  <strong>Problem:</strong>
  <%= @txdotstreet.problem.humanize %>
</p>

<p>
  <strong>City:</strong>
  <%= @txdotstreet.city_to_string.humanize %>
</p>

<p>
  <strong>State:</strong>
  <%= @txdotstreet.state_to_string.humanize %>
</p>

<p>
  <strong>Needed:</strong>
  <%= @txdotstreet.needed.humanize %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @txdotstreet.comment.humanize %>
</p>

<%= link_to 'Edit', edit_txdotstreet_path(@txdotstreet) %> |
<%= link_to 'Back', txdotstreets_path %>