config/routes.rb
Rails.application.routes.draw do
  resources :trouble911s
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Lockup::Engine, at: '/lockup'
  resources :georeports
  resources :txdotstreets
  resources :txdotlights
  resources :genericcallouts
  resources :citystreets
  resources :watersewers
  resources :animalcontrols
  resources :cchlogs
  resources :daysoffrequests
  resources :ithelptickets
  resources :fleettickets
  resources :radionumbers
  resources :vacationpatrols
  resources :sexoffenders do
    resources :comments
  end
  resources :phonenumbers
  resources :gatecodes
  resources :rollcalls
  resources :sessions
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "/pages/:page" => "pages#show"
  resources :users
  get 'dashboard/index'
  get '/dailydispatch' => 'dailydispatch#index.html.erb'
  root 'dashboard#index'

end

app/models/txdotlight.rb
class Txdotlight < ApplicationRecord
  def city_to_string
    city ? 'Yes' : 'No'
  end

  def state_to_string
    state ? 'Yes' : 'No'
  end

  def lightout_to_string
    lightout ? 'Yes' : 'No'
  end

  def lightred_to_string
    lightred ? 'Yes' : 'No'
  end
  validates :intersection,
            presence: true,
            length: {maximum: 140},
            allow_nil: false
  validates :name,
            presence: true,
            length: {maximum: 140},
            allow_nil: false
  validates :callback,
            presence: true,
            length: {maximum: 140},
            allow_nil: false
  validates :unitassigned,
            presence: true,
            length: {maximum: 140},
            allow_nil: false
  validates :problem,
            presence: true,
            length: {maximum: 400 },
            allow_nil: false
  validates :comment,
            length: {maximum: 400 },
            allow_nil: false
end

app/controllers/txdotlights_controller.rb
class TxdotlightsController < ApplicationController
  load_and_authorize_resource
  before_action :set_txdotlight, only: [:show, :edit, :update, :destroy]

  # GET /txdotlights
  # GET /txdotlights.json
  def index
    @txdotlights = Txdotlight.all.paginate(:per_page =>15, :page => params[:page])
                       .where("intersection ILIKE ?","%#{params[:address_search]}%").where("name ILIKE ?","%#{params[:name_search]}%").where("callback ILIKE ?","%#{params[:phone_search]}%").where("unitassigned ILIKE ?","%#{params[:unit_search]}%")
  end

  # GET /txdotlights/1
  # GET /txdotlights/1.json
  def show
  end

  # GET /txdotlights/new
  def new
    @txdotlight = Txdotlight.new
  end

  # GET /txdotlights/1/edit
  def edit
  end

  # POST /txdotlights
  # POST /txdotlights.json
  def create
    @txdotlight = Txdotlight.new(txdotlight_params)

    respond_to do |format|
      if @txdotlight.save
        format.html { redirect_to @txdotlight, notice: 'TX-DOT Light Call-Out was successfully created.' }
        format.json { render :show, status: :created, location: @txdotlight }
      else
        format.html { render :new }
        format.json { render json: @txdotlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /txdotlights/1
  # PATCH/PUT /txdotlights/1.json
  def update
    respond_to do |format|
      if @txdotlight.update(txdotlight_params)
        format.html { redirect_to @txdotlight, notice: 'TX-DOT Light Call-Out was successfully updated.' }
        format.json { render :show, status: :ok, location: @txdotlight }
      else
        format.html { render :edit }
        format.json { render json: @txdotlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /txdotlights/1
  # DELETE /txdotlights/1.json
  def destroy
    @txdotlight.destroy
    respond_to do |format|
      format.html { redirect_to txdotlights_url, notice: 'TX-DOT Light Call-Out was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_txdotlight
      @txdotlight = Txdotlight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def txdotlight_params
      params.require(:txdotlight).permit(:intersection, :name, :callback, :unitassigned, :problem, :city, :state, :lightout, :lightred, :comment)
    end
end

app/helpers/txdotlights_helper.rb
module TxdotlightsHelper
end

app/views/txdotlights/_form.html.erb
<%= form_with(model: txdotlight, local: true) do |form| %>
  <% if txdotlight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(txdotlight.errors.count, "error") %> prohibited this txdotlight from being saved:</h2>

      <ul>
      <% txdotlight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :intersection %>
    <%= form.text_field :intersection, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :callback, "Call Back" %>
    <%= form.text_field :callback, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :unitassigned, "Unit Assigned" %>
    <%= form.text_field :unitassigned, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :problem %>
    <%= form.text_area :problem, maxlength: 400 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.check_box :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.check_box :state %>
  </div>

  <div class="field">
    <%= form.label :lightout %>
    <%= form.check_box :lightout %>
  </div>

  <div class="field">
    <%= form.label :lightred %>
    <%= form.check_box :lightred %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, maxlength: 400 %>
  </div>

  <div class="actions">
    <%= form.submit "Submit" %>
  </div>
<% end %>

app/views/txdotlights/edit.html.erb
<h1>Editing TX-DOT Light Call-Out</h1>

<%= render 'form', txdotlight: @txdotlight %>

<%= link_to 'Show', @txdotlight %> |
<%= link_to 'Back', txdotlights_path %>

app/views/txdotlights/index.html.erb
<p id="notice"><%= notice %></p>
<div id="search">
  <%= form_tag txdotlights_path, :method => 'get' do %>
    <%= text_field_tag :address_search, params[:address_search], :placeholder => "Address" %>
    <%= text_field_tag :name_search, params[:name_search], :placeholder => "Name" %>
    <%= text_field_tag :phone_search, params[:phone_search], :placeholder => "Callback Number" %>
    <%= text_field_tag :unit_search, params[:unit_search], :placeholder => "Unit Number" %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

<div class="apple_pagination">
  <%= will_paginate @txdotlights %>
</div>

<center>

<h1>TX-DOT Signal Light Call-Out</h1>

<table>
  <thead>
    <tr>
      <th>Intersection</th>
      <th>Name</th>
      <th>Call Back</th>
      <th>Unit Assigned</th>
      <th>Problem</th>
      <th>City</th>
      <th>State</th>
      <th>Lightout</th>
      <th>Lightred</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @txdotlights.each do |txdotlight| %>
      <tr>
        <td><%= txdotlight.intersection.humanize %></td>
        <td><%= txdotlight.name.humanize.titleize %></td>
        <td><%= txdotlight.callback.humanize %></td>
        <td><%= txdotlight.unitassigned.humanize %></td>
        <td><%= txdotlight.problem.humanize %></td>
        <td><%= txdotlight.city_to_string.humanize %></td>
        <td><%= txdotlight.state_to_string.humanize %></td>
        <td><%= txdotlight.lightout_to_string.humanize %></td>
        <td><%= txdotlight.lightred_to_string.humanize %></td>
        <td><%= txdotlight.comment.humanize %></td>
        <td><%= link_to '', txdotlight, class: "far fa-eye"
        %></td>
        <td><%= link_to '', edit_txdotlight_path(txdotlight), class: "far fa-edit"
        %></td>
        <% if can? :delete, :all %>
      <td><%= link_to '', txdotlight, method: :delete, data: { confirm: 'Are you sure?' }, class: "far fa-trash-alt" %></td>
          <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Call-Out', new_txdotlight_path %>
  <br />-
  <br />
  <a href="/pages/afterhours.html">Back to After Hours Call-Out</a>
</center>

app/views/txdotlights/new.html.erb
<h1>New TX-DOT Signal Light Call-Out</h1>

<%= render 'form', txdotlight: @txdotlight %>

<%= link_to 'Back', txdotlights_path %>

app/views/txdotlights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Intersection:</strong>
  <%= @txdotlight.intersection.humanize %>
</p>

<p>
  <strong>Name:</strong>
  <%= @txdotlight.name.humanize.titleize %>
</p>

<p>
  <strong>Call Back:</strong>
  <%= @txdotlight.callback.humanize %>
</p>

<p>
  <strong>Unit Assigned:</strong>
  <%= @txdotlight.unitassigned.humanize %>
</p>

<p>
  <strong>Problem:</strong>
  <%= @txdotlight.problem.humanize %>
</p>

<p>
  <strong>City:</strong>
  <%= @txdotlight.city_to_string.humanize %>
</p>

<p>
  <strong>State:</strong>
  <%= @txdotlight.state_to_string.humanize %>
</p>

<p>
  <strong>Lightout:</strong>
  <%= @txdotlight.lightout_to_string.humanize %>
</p>

<p>
  <strong>Lightred:</strong>
  <%= @txdotlight.lightred_to_string.humanize %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @txdotlight.comment.humanize %>
</p>

<%= link_to 'Edit', edit_txdotlight_path(@txdotlight) %> |
<%= link_to 'Back', txdotlights_path %>