config/routes.rb
Rails.application.routes.draw do
  resources :trouble911s
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Lockup::Engine, at: '/lockup'
  resources :georeports
  resources :txdotstreets
  resources :txdotlights
  resources :genericcallouts
  resources :citystreets
  resources :watersewers
  resources :animalcontrols
  resources :cchlogs
  resources :daysoffrequests
  resources :ithelptickets
  resources :fleettickets
  resources :radionumbers
  resources :vacationpatrols
  resources :sexoffenders do
    resources :comments
  end
  resources :phonenumbers
  resources :gatecodes
  resources :rollcalls
  resources :sessions
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "/pages/:page" => "pages#show"
  resources :users
  get 'dashboard/index'
  get '/dailydispatch' => 'dailydispatch#index.html.erb'
  root 'dashboard#index'

end

app/models/cchlog.rb
class Cchlog < ApplicationRecord
  REASONS = %i[investigation arrest TCIC_entry other grand_jury]
  DISPOSITIONS =%i[file destroy]

  validates_date :dateofbirth, :on_or_before => lambda {Date.current}
  validates :name,
            presence: true,
            length: {maximum: 140},
            allow_nil: false
  validates :idnum,
            presence: true,
            length: {maximum: 140},
            allow_nil: false
  validates :operator,
            presence: true,
            length: {maximum: 140},
            allow_nil: false
  validates :officer,
            presence: true,
            length: {maximum: 140},
            allow_nil: false
  validates :dateofbirth,
            presence: true,
            allow_nil: false
end

app/controllers/cchlogs_controller.rb
class CchlogsController < ApplicationController
  load_and_authorize_resource
  before_action :set_cchlog, only: [:show, :edit, :update, :destroy]

  # GET /cchlogs
  # GET /cchlogs.json
  def index
        @cchlogs = Cchlog.all.paginate(:per_page =>15, :page => params[:page])
                       .where("name ILIKE ?","%#{params[:name_search]}%")
                       .where("idnum ILIKE ?","%#{params[:id_search]}%")
                       .where("reason ILIKE ?","%#{params[:reason_search]}%")
                       .where("officer ILIKE ?","%#{params[:officer_search]}%")
  end

  # GET /cchlogs/1
  # GET /cchlogs/1.json
  def show
  end

  # GET /cchlogs/new
  def new
    @cchlog = Cchlog.new
  end

  # GET /cchlogs/1/edit
  def edit
  end

  # POST /cchlogs
  # POST /cchlogs.json
  def create
    @cchlog = Cchlog.new(cchlog_params)

    respond_to do |format|
      if @cchlog.save
        format.html { redirect_to @cchlog, notice: 'CCH Log was successfully created.' }
        format.json { render :show, status: :created, location: @cchlog }
      else
        format.html { render :new }
        format.json { render json: @cchlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cchlogs/1
  # PATCH/PUT /cchlogs/1.json
  def update
    respond_to do |format|
      if @cchlog.update(cchlog_params)
        format.html { redirect_to @cchlog, notice: 'CCH Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @cchlog }
      else
        format.html { render :edit }
        format.json { render json: @cchlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cchlogs/1
  # DELETE /cchlogs/1.json
  def destroy
    @cchlog.destroy
    respond_to do |format|
      format.html { redirect_to cchlogs_url, notice: 'CCH Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cchlog
      @cchlog = Cchlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cchlog_params
      params.require(:cchlog).permit(:name, :dateofbirth, :idnum, :operator, :reason, :officer, :disposition, :dispositiondate, :comment)
    end
end

app/helpers/cchlogs_helper.rb
module CchlogsHelper
end

app/views/cchlogs/_form.html.erb
<%= form_with(model: cchlog, local: true) do |form| %>
  <% if cchlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cchlog.errors.count, "error") %> prohibited this cchlog from being saved:</h2>

      <ul>
      <% cchlog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :dateofbirth, "DOB" %>
    <%= form.date_select :dateofbirth %>
  </div>

  <div class="field">
    <%= form.label :idnum, "ID" %>
    <%= form.text_field :idnum, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :operator%>
    <%= form.text_field :operator, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :reason %>
    <%= form.collection_select(:reason, Cchlog::REASONS, :to_s, lambda{|i| i.to_s.humanize}) %>

  </div>

  <div class="field">
    <%= form.label :officer %>
    <%= form.text_field :officer, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :disposition %>
    <%= form.collection_select(:disposition, Cchlog::DISPOSITIONS, :to_s, lambda{|i| i.to_s.humanize}) %>
  </div>

  <div class="field">
    <%= form.label :dispositiondate, "Disposition Date"%>
    <%= form.date_select :dispositiondate %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, maxlength: 400 %>
  </div>

  <div class="actions">
    <%= form.submit "Submit"%>
  </div>
<% end %>

app/views/cchlogs/edit.html.erb
<h1>Editing Cchlog</h1>

<%= render 'form', cchlog: @cchlog %>

<%= link_to 'Show', @cchlog %> |
<%= link_to 'Back', cchlogs_path %>

app/views/cchlogs/index.html.erb
<center>
<p id="notice"><%= notice %></p>
  <div id="search">
    <%= form_tag cchlogs_path, :method => 'get' do %>
      <%= text_field_tag :name_search, params[:name_search], :placeholder => "Name" %>
      <%= text_field_tag :id_search, params[:id_search], :placeholder => "ID Number"%>
      <%= text_field_tag :reason_search, params[:reason_search], :placeholder => "Reason"%>
      <%= text_field_tag :officer_search, params[:officer_search], :placeholder => "Officer"%>
      <%= submit_tag "Search" %>
    <% end %>
  </div>
  <div class="apple_pagination">
    <%= will_paginate @cchlogs %>
  </div>
<h1>CCH Log Review</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>DOB</th>
      <th>ID</th>
      <th>Operator</th>
      <th>Reason</th>
      <th>Officer</th>
      <th>Disposition</th>
      <th>Disposition Date</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cchlogs.each do |cchlog| %>
      <tr>
        <td><%= cchlog.name.humanize.titleize %></td>
        <td><%= cchlog.dateofbirth %></td>
        <td><%= cchlog.idnum.humanize %></td>
        <td><%= cchlog.operator.humanize.titleize %></td>
        <td><%= cchlog.reason.humanize %></td>
        <td><%= cchlog.officer.humanize.titleize %></td>
        <td><%= cchlog.disposition.humanize %></td>
        <td><%= cchlog.dispositiondate %></td>
        <td><%= cchlog.comment.humanize %></td>
        <td><%= link_to '', cchlog, class: "far fa-eye"
        %></td>
        <td><%= link_to '', edit_cchlog_path(cchlog), class: "far fa-edit"
        %></td>
        <% if can? :delete, :all %>

      <td><%= link_to '', cchlog, method: :delete, data: { confirm: 'Are you sure?' }, class: "far fa-trash-alt" %></td>
          <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cchlog', new_cchlog_path %>
</center>

app/views/cchlogs/new.html.erb
<h1>New CCH Log</h1>

<%= render 'form', cchlog: @cchlog %>

<%= link_to 'Back', cchlogs_path %>

app/views/cchlogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cchlog.name.humanize.titleize %>
</p>

<p>
  <strong>Dateofbirth:</strong>
  <%= @cchlog.dateofbirth %>
</p>

<p>
  <strong>Idnum:</strong>
  <%= @cchlog.idnum.humanize %>
</p>

<p>
  <strong>Operator:</strong>
  <%= @cchlog.operator.humanize.titleize %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @cchlog.reason.humanize %>
</p>

<p>
  <strong>Officer:</strong>
  <%= @cchlog.officer.humanize.titleize %>
</p>

<p>
  <strong>Disposition:</strong>
  <%= @cchlog.disposition.humanize %>
</p>

<p>
  <strong>Dispositiondate:</strong>
  <%= @cchlog.dispositiondate %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @cchlog.comment.humanize %>
</p>

<%= link_to 'Edit', edit_cchlog_path(@cchlog) %> |
<%= link_to 'Back', cchlogs_path %>