config/routes.rb
Rails.application.routes.draw do
  resources :trouble911s
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Lockup::Engine, at: '/lockup'
  resources :georeports
  resources :txdotstreets
  resources :txdotlights
  resources :genericcallouts
  resources :citystreets
  resources :watersewers
  resources :animalcontrols
  resources :cchlogs
  resources :daysoffrequests
  resources :ithelptickets
  resources :fleettickets
  resources :radionumbers
  resources :vacationpatrols
  resources :sexoffenders do
    resources :comments
  end
  resources :phonenumbers
  resources :gatecodes
  resources :rollcalls
  resources :sessions
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "/pages/:page" => "pages#show"
  resources :users
  get 'dashboard/index'
  get '/dailydispatch' => 'dailydispatch#index.html.erb'
  root 'dashboard#index'

end

app/models/phonenumber.rb
class Phonenumber < ApplicationRecord
  validates :name,
            presence: true,
            length: {maximum: 140},
            allow_nil: false,
            format: { with: /\A^[\p{L}\s'.-]+$\z/,
                      message: "only allows letters, dashes, apostrophes, and periods." }

  validates :home,
            length: {maximum: 140},
            allow_nil: false

  validates :office,
            length: {maximum: 140},
            allow_nil: false

  validates :cell,
            length: {maximum: 140},
            allow_nil: false

  validates :secondary_contact,
            length: {maximum: 140},
            allow_nil: false

  validate :any_present?

  def any_present?
    if %w(home office cell secondary_contact).all?{|attr| self[attr].blank?}
      errors.add :base, "At least one phone number must be entered."
    end
  end

end

app/controllers/phonenumbers_controller.rb
class PhonenumbersController < ApplicationController
  load_and_authorize_resource
  before_action :set_phonenumber, only: [:show, :edit, :update, :destroy]

  # GET /phonenumbers
  # GET /phonenumbers.json
  def index
    @phonenumbers = Phonenumber.all.paginate(:per_page =>15, :page => params[:page])
                        .where("name ILIKE ?","%#{params[:name_search]}%").where("home ILIKE ?","%#{params[:home_search]}%").where("office ILIKE ?","%#{params[:office_search]}%").where("cell ILIKE ?","%#{params[:cell_search]}%")
  end

  # GET /phonenumbers/1
  # GET /phonenumbers/1.json
  def show
  end

  # GET /phonenumbers/new
  def new
    @phonenumber = Phonenumber.new
  end

  # GET /phonenumbers/1/edit
  def edit
  end

  # POST /phonenumbers
  # POST /phonenumbers.json
  def create
    @phonenumber = Phonenumber.new(phonenumber_params)

    respond_to do |format|
      if @phonenumber.save
        format.html { redirect_to @phonenumber, notice: 'Phone Number was successfully created.' }
        format.json { render :show, status: :created, location: @phonenumber }
      else
        format.html { render :new }
        format.json { render json: @phonenumber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phonenumbers/1
  # PATCH/PUT /phonenumbers/1.json
  def update
    respond_to do |format|
      if @phonenumber.update(phonenumber_params)
        format.html { redirect_to @phonenumber, notice: 'Phone Number was successfully updated.' }
        format.json { render :show, status: :ok, location: @phonenumber }
      else
        format.html { render :edit }
        format.json { render json: @phonenumber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phonenumbers/1
  # DELETE /phonenumbers/1.json
  def destroy
    @phonenumber.destroy
    respond_to do |format|
      format.html { redirect_to phonenumbers_url, notice: 'Phone Number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phonenumber
      @phonenumber = Phonenumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phonenumber_params
      params.require(:phonenumber).permit(:name, :home, :office, :cell, :secondary_contact)
    end
end

app/helpers/phonenumbers_helper.rb
module PhonenumbersHelper
end

app/views/phonenumbers/_form.html.erb
<%= form_with(model: phonenumber, local: true) do |form| %>
  <% if phonenumber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phonenumber.errors.count, "error") %> prohibited this phonenumber from being saved:</h2>

      <ul>
      <% phonenumber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :home %>
    <%= form.text_field :home, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :office %>
    <%= form.text_field :office, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :cell %>
    <%= form.text_field :cell, maxlength: 140, size: 30 %>
  </div>

  <div class="field">
    <%= form.label :secondary_contact %>
    <%= form.text_field :secondary_contact, maxlength: 140, size: 30 %>
  </div>

  <div class="actions">
    <%= form.submit "Add Phone Number" %>
  </div>
<% end %>

app/views/phonenumbers/edit.html.erb
<h1>Editing Phonenumber</h1>

<%= render 'form', phonenumber: @phonenumber %>

<%= link_to 'Show', @phonenumber %> |
<%= link_to 'Back', phonenumbers_path %>

app/views/phonenumbers/index.html.erb
<p id="notice"><%= notice %></p>

<div id="search">
  <%= form_tag phonenumbers_path, :method => 'get' do %>
    <%= text_field_tag :name_search, params[:name_search], :placeholder => "Name" %>
    <%= text_field_tag :home_search, params[:home_search], :placeholder => "Home Number", :type => "number" %>
    <%= text_field_tag :office_search, params[:office_search], :placeholder => "Office Number", :type => "number" %>
    <%= text_field_tag :cell_search, params[:cell_search], :placeholder => "Cell Number", :type => "number" %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

<div class="apple_pagination">
  <%= will_paginate @phonenumbers %>
</div>

<h1>Phone Directory</h1>

<table class="center">
  <thead>
    <tr>
      <th>Name</th>
      <th>Home</th>
      <th>Office</th>
      <th>Cell</th>
      <th>Secondary Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phonenumbers.each do |phonenumber| %>
      <tr>
        <td><%= phonenumber.name.humanize.titleize %></td>
        <td><%= phonenumber.home.humanize %></td>
        <td><%= phonenumber.office.humanize %></td>
        <td><%= phonenumber.cell.humanize %></td>
        <td><%= phonenumber.secondary_contact.humanize.titleize %></td>
        <td><%= link_to '', phonenumber, class: "far fa-eye"
        %></td>
        <td><%= link_to '', edit_phonenumber_path(phonenumber), class: "far fa-edit"
        %></td>
        <% if can? :delete, :all %>
      <td><%= link_to '', phonenumber, method: :delete, data: { confirm: 'Are you sure?' }, class: "far fa-trash-alt" %></td>
          <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone Number', new_phonenumber_path %>

app/views/phonenumbers/new.html.erb
<h1>New Phone Number</h1>

<%= render 'form', phonenumber: @phonenumber %>

<%= link_to 'Back', phonenumbers_path %>

app/views/phonenumbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @phonenumber.name.humanize.titleize %>
</p>

<p>
  <strong>Home:</strong>
  <%= @phonenumber.home.humanize %>
</p>

<p>
  <strong>Office:</strong>
  <%= @phonenumber.office.humanize %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @phonenumber.cell.humanize %>
</p>

<p>
  <strong>Secondary contact:</strong>
  <%= @phonenumber.secondary_contact.humanize.titleize %>
</p>

<%= link_to 'Edit', edit_phonenumber_path(@phonenumber) %> |
<%= link_to 'Back', phonenumbers_path %>